<a href="https://colab.research.google.com/github/husthorng/hello-world/blob/main/_backpropagation_4x1y_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [ ]:
nonlin(5.71,deriv=False)

0.9966982650219125

In [ ]:
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array([[0],
            [1],
            [1],
            [0]])

In [ ]:
import csv
import pandas as pd

numTag=1   #   輸出的數目
nnode=4
url = "exdata4X1y.csv"
records = pd.read_csv(url,encoding='utf-8',header=None)
Xi=records.iloc[0:records.shape[0],0:records.shape[1]-numTag].values
y=records.iloc[:,list(records.shape[1]-np.arange(numTag,0,-1))].values

In [ ]:
Xi

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 1, 0]])

In [ ]:
X=np.insert(Xi,Xi[0].size,1,axis=1)

In [ ]:
X[0]

In [ ]:

y

array([[1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [ ]:
np.random.seed(1)
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((X[0].size,nnode)) - 1
syn1 = 2*np.random.random((nnode+1,numTag)) - 1



In [ ]:
syn0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ],
       [-0.5910955 ,  0.75623487, -0.94522481,  0.34093502],
       [-0.1653904 ,  0.11737966, -0.71922612, -0.60379702]])

In [ ]:
syn1

array([[ 0.60148914],
       [ 0.93652315],
       [-0.37315164],
       [ 0.38464523],
       [ 0.7527783 ]])

In [ ]:
l0 = X
l1 = nonlin(np.dot(l0,syn0))
l1=np.insert(l1,l1[0].size,1,axis=1)
l2 = nonlin(np.dot(l1,syn1))
l2_error = y - l2

In [ ]:
print(X)
print(syn0)

[[0 0 1 1 1]
 [0 1 1 0 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 1]
 [1 1 0 0 1]
 [1 1 1 0 1]
 [1 0 1 0 1]]
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]
 [-0.5910955   0.75623487 -0.94522481  0.34093502]
 [-0.1653904   0.11737966 -0.71922612 -0.60379702]]


In [ ]:
l0 = X
np.dot(l0,syn0)


array([[-0.96295095,  0.951248  , -1.82606191,  0.107577  ],
       [-1.07834367, -0.62030969, -1.50831667, -0.54223657],
       [-1.12890694,  1.39189698, -2.82583316, -0.28775786],
       [-1.83539516,  0.57657417, -3.45331274, -0.5966364 ],
       [-0.37185545,  0.19501312, -0.88083709, -0.23335802],
       [-1.0378346 , -0.25729417, -2.34647695, -1.30801042],
       [-1.24429966, -0.1796607 , -2.50808792, -0.93757142],
       [-0.53781144,  0.63566211, -1.88060834, -0.62869288]])

In [ ]:
nonlin(np.dot(l0,syn0))

array([[0.27628776, 0.72136609, 0.13870808, 0.52686834],
       [0.25381959, 0.34971102, 0.1811884 , 0.36766745],
       [0.24436288, 0.80089491, 0.05594406, 0.42855287],
       [0.13759681, 0.64027874, 0.03067022, 0.35511361],
       [0.40809276, 0.54859936, 0.29300434, 0.44192381],
       [0.26156802, 0.43602898, 0.08734621, 0.21281996],
       [0.22368846, 0.45520525, 0.07529313, 0.28139117],
       [0.36869684, 0.65377222, 0.13231901, 0.34780698]])

In [ ]:
l1

array([[0.27628776, 0.72136609, 0.13870808, 0.52686834, 1.        ],
       [0.25381959, 0.34971102, 0.1811884 , 0.36766745, 1.        ],
       [0.24436288, 0.80089491, 0.05594406, 0.42855287, 1.        ],
       [0.13759681, 0.64027874, 0.03067022, 0.35511361, 1.        ],
       [0.40809276, 0.54859936, 0.29300434, 0.44192381, 1.        ],
       [0.26156802, 0.43602898, 0.08734621, 0.21281996, 1.        ],
       [0.22368846, 0.45520525, 0.07529313, 0.28139117, 1.        ],
       [0.36869684, 0.65377222, 0.13231901, 0.34780698, 1.        ]])

In [ ]:
syn0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ],
       [-0.5910955 ,  0.75623487, -0.94522481,  0.34093502],
       [-0.1653904 ,  0.11737966, -0.71922612, -0.60379702]])

In [ ]:
np.dot(l1,syn1)

array([[1.74543668],
       [1.30677128],
       [1.79378175],
       [1.56032527],
       [1.5726665 ],
       [1.36772666],
       [1.39377475],
       [1.67122551]])

In [ ]:
l2=nonlin(np.dot(l1,syn1))
l2

array([[0.85137631],
       [0.78697237],
       [0.8573903 ],
       [0.82640002],
       [0.82816341],
       [0.79701261],
       [0.80119418],
       [0.84173914]])

In [ ]:
y - l2

array([[ 0.14862369],
       [-0.78697237],
       [ 0.1426097 ],
       [-0.82640002],
       [-0.82816341],
       [ 0.20298739],
       [ 0.19880582],
       [-0.84173914]])

In [ ]:
l2_delta = l2_error*nonlin(l2,deriv=True)
l2_delta

array([[ 0.01880605],
       [-0.13193344],
       [ 0.0174372 ],
       [-0.11855785],
       [-0.11785492],
       [ 0.03284001],
       [ 0.0316662 ],
       [-0.11213174]])

In [ ]:
l1_error=l2_delta.dot(syn1.T)
l1_error

array([[ 0.01131164,  0.0176123 , -0.00701751,  0.00723366,  0.01415679],
       [-0.07935653, -0.12355873,  0.04923118, -0.05074757, -0.09931663],
       [ 0.01048828,  0.01633034, -0.00650672,  0.00670713,  0.01312634],
       [-0.07131126, -0.11103217,  0.04424006, -0.04560271, -0.08924778],
       [-0.07088846, -0.11037386,  0.04397776, -0.04533233, -0.08871863],
       [ 0.01975291,  0.03075543, -0.0122543 ,  0.01263175,  0.02472125],
       [ 0.01904688,  0.02965613, -0.0118163 ,  0.01218025,  0.02383763],
       [-0.06744602, -0.10501397,  0.04184214, -0.04313094, -0.08441034]])

In [ ]:
l1_delta = l1_error * nonlin(l1,deriv=True)

In [ ]:
l1.T.dot(l2_delta)


array([[-0.11410869],
       [-0.20374717],
       [-0.06807341],
       [-0.14841156],
       [-0.37972849]])

In [ ]:
a=syn1+l1.T.dot(l2_delta)
a

array([[ 0.48738045],
       [ 0.73277598],
       [-0.44122506],
       [ 0.23623367],
       [ 0.37304981]])

In [ ]:
b=l0.T.dot(l1_delta)[:,:-1]
b

array([[-0.01510131, -0.03182188,  0.00397594, -0.0140054 ],
       [-0.01636902, -0.0387545 ,  0.00681956, -0.01766245],
       [-0.04880787, -0.09127652,  0.02052846, -0.03729677],
       [-0.00426362, -0.01942904,  0.00013322, -0.00699764],
       [-0.04499259, -0.08371353,  0.01955159, -0.0351806 ]])

In [ ]:
syn0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ],
       [-0.5910955 ,  0.75623487, -0.94522481,  0.34093502],
       [-0.1653904 ,  0.11737966, -0.71922612, -0.60379702]])

In [ ]:
for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l1=np.insert(l1,l1[0].size,1,axis=1)
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2

    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))

    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)

    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)[:,:-1]


Error:0.49703769282908905
Error:0.006160708519518814
Error:0.004190435976085491
Error:0.003360664294740008
Error:0.0028783078771088162
Error:0.002554388926005436


In [ ]:
syn1

array([[ 7.66137175],
       [12.38983421],
       [-9.2833714 ],
       [-6.48193551],
       [ 0.60008338]])

In [ ]:
import numpy as np
syn0=np.array([[ 2.58124076, -0.06893844, -5.56808533, -1.20729539],
       [-0.56194801, -6.33335632, -1.29760143,  0.6457777 ],
       [-2.0393265 ,  1.36316137,  2.3763829 ,  2.19240479],
       [-2.62104582, -4.91395889, -7.72245903,  1.33584484],
       [-0.1280758 ,  7.03370268,  1.13354858, -0.09640023]])

syn1=np.array([[  3.2736903 ],
       [ 12.89446755],
       [-13.24322306],
       [ -3.99138576],
       [ -2.77186187]])
XXa=np.array([0,0,1,1])
XX=np.insert(XXa,XXa.size,1)
print(np.dot(XX,syn0))
#for (j=0; j<5; j++){
#    print(i)
#    }

[-4.78844812  3.48290516 -4.21252755  3.4318494 ]


In [ ]:
syn1[0][0]

3.2736903

In [ ]:
XX1=nonlin(np.dot(XX,syn0))
XX1

array([0.00825663, 0.97019744, 0.01459279, 0.96868522])

In [ ]:
XX1.size

4

In [ ]:
XX2=np.insert(XX1,XX1.size,1)
XX2

array([0.00825663, 0.97019744, 0.01459279, 0.96868522, 1.        ])

In [ ]:
np.dot(XX2,syn1)

array([5.7056952])

In [ ]:
nonlin(np.dot(XX2,syn1))

array([0.99668407])

In [ ]:
syn1

array([[  3.2736903 ],
       [ 12.89446755],
       [-13.24322306],
       [ -3.99138576],
       [ -2.77186187]])

In [ ]:
X[0]
X

array([[0, 0, 1, 1, 1],
       [0, 1, 1, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1],
       [1, 1, 1, 0, 1]])

In [ ]:
#print output
print("output after Training:")
print(l2)

output after Training:
[[9.97292001e-01]
 [8.87730908e-04]
 [9.98683338e-01]
 [2.72015225e-03]
 [2.11085118e-03]
 [9.99332995e-01]
 [9.98620044e-01]]
