<a href="https://colab.research.google.com/github/husthorng/hello-world/blob/neural_networks_4X2y/backpropagation_4x2y.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

import csv
import pandas as pd

numTag=2   #   輸出的數目
nnode=4
url = "https://raw.githubusercontent.com/husthorng/Backpropagation_NN/main/exdata4X2y.csv"
records = pd.read_csv(url,encoding='utf-8',header=None)
Xi=records.iloc[0:records.shape[0],0:records.shape[1]-numTag].values
y=records.iloc[:,list(records.shape[1]-np.arange(numTag,0,-1))].values

X=np.insert(Xi,Xi[0].size,1,axis=1)
np.random.seed(1)
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((X[0].size,nnode)) - 1
syn1 = 2*np.random.random((nnode+1,numTag)) - 1

for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l1=np.insert(l1,l1[0].size,1,axis=1)
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2

    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))

    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)

    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)[:,:-1]

#print output
print("output after Training:")
print(l2)

Error:0.4980534168902378
Error:0.005902032130759731
Error:0.004056950373963072
Error:0.003270620247363478
Error:0.0028105426293095863
Error:0.002500240080621688
output after Training:
[[9.97235679e-01 9.97325994e-01]
 [2.03771833e-03 9.99995063e-01]
 [9.97145585e-01 3.57892934e-03]
 [4.42623428e-03 1.03936301e-05]
 [2.43049239e-03 9.99998142e-01]
 [9.99744573e-01 9.96353465e-01]
 [9.96341559e-01 3.47982677e-03]]


In [ ]:
syn0

array([[-4.35491885,  6.33096348, -5.81280878,  0.71073579],
       [-0.1535507 ,  0.41335711, -0.44124504,  4.97236024],
       [-5.63332814, -1.44982941,  0.35258915,  0.78357392],
       [ 0.25345681,  5.18569569, -3.70126497,  5.05058305],
       [ 7.07183028, -1.25418903,  2.09417836, -8.71029492]])

array([[-4.35491885,  6.33096348, -5.81280878,  0.71073579],
       [-0.1535507 ,  0.41335711, -0.44124504,  4.97236024],
       [-5.63332814, -1.44982941,  0.35258915,  0.78357392],
       [ 0.25345681,  5.18569569, -3.70126497,  5.05058305],
       [ 7.07183028, -1.25418903,  2.09417836, -8.71029492]])

In [ ]:
syn1

array([[  2.07935484,  12.46266627],
       [  8.79461484,  -4.25471526],
       [ -7.12424243,   5.3049791 ],
       [-13.39786643,  -6.82527069],
       [ -1.68811209,  -1.48972636]])

array([[  2.07935484,  12.46266627],
       [  8.79461484,  -4.25471526],
       [ -7.12424243,   5.3049791 ],
       [-13.39786643,  -6.82527069],
       [ -1.68811209,  -1.48972636]])